{% set name = "blacktex" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blacktex-{{ version }}.tar.gz
  sha256: fd6d25906cb024801730c22145b14ea93d192a077bf56be4e6b1514d44a55b9f

build:
  number: 1
  noarch: python
  entry_points:
    - blacktex = blacktex.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.2,<4
  run:
    - python >={{ python_min }}
    - importlib-metadata

test:
  imports:
    - blacktex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nschloe/blacktex
  summary: Cleans up your LaTeX files
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    `blacktex` is a little tool, helping with the article editing 
    for LaTeX. It removes all comments from a given file and corrects 
    some common anti-patterns.

    PyPI: [https://pypi.org/project/blacktex/](https://pypi.org/project/blacktex/)

  doc_url: https://github.com/nschloe/blacktex
  dev_url: https://github.com/nschloe/blacktex

extra:
  recipe-maintainers:
    - sugatoray
